In [1]:
import numpy as np
import sympy as sp

In [2]:
a = np.array([[1, 2, -1], [3, 1, 0]])
b = np.array([[-2, 1], [0, -3], [2, 1]])
np.dot(a, b)

array([[-4, -6],
       [-6,  0]])

In [3]:
a = np.array([[1, 0, 0],
[0, 1, 0],
[-2, 0, 1]])
b = np.array([[1, 0, 0],
[0, 1, 0],
[2, 0, 1]])
np.dot(a, b)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
a = np.array([[4, 3], [6, 5]])
np.linalg.det(a)

1.999999999999998

In [5]:
a = np.array([[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]])
b = np.array([[3, -2, -5, 0]]).reshape(-1, 1)
np.dot(np.linalg.inv(a), b)

array([[ 4.],
       [ 3.],
       [-5.],
       [ 1.]])

In [6]:
a = np.array([[3, 7, 1], [-2, 1, 1], [5, -2, 1]])
np.linalg.det(a)

57.00000000000001

In [7]:
a = np.array([[-1, 2, 3, -1]]).reshape(-1, 1)
b = np.array([[2, 1, 0, 2]]).reshape(-1, 1)
inner_product = 0
for comp in zip(a, b):
    inner_product += comp[0] * comp[1]
int(inner_product)

-2

In [8]:
t1 = np.array([1, 1]).reshape(-1, 1)
t2 = np.array([1, -1]).reshape(-1, 1)
t = np.hstack([t1, t2])
x = np.array([5, -2]).reshape(-1, 1)
y = np.array([3, 4]).reshape(-1, 1)
np.dot(np.linalg.inv(t), x), np.dot(np.linalg.inv(t), y), np.dot(np.linalg.inv(t), x + y)

(array([[1.5],
        [3.5]]),
 array([[ 3.5],
        [-0.5]]),
 array([[5.],
        [3.]]))

In [9]:
A = np.array([[1, 1, 2], [3, 4, 1], [3, 7, 1], [4, 2, 3]])
b = np.array([11, 2, -7, 21]).reshape(-1, 1)
np.dot(np.dot(np.linalg.inv(np.dot(A.transpose(), A)), A.transpose()), b)

array([[ 2.51428571],
       [-2.85714286],
       [ 5.6       ]])

In [10]:
a = np.array([[1, 2, 2], [1, 2, -1], [3, -3, 0]])
np.linalg.det(a)

-27.0

In [11]:
a = np.array([[4, 1], [5, 1]])
np.linalg.det(a)

-0.9999999999999998

In [12]:
a = np.array([[1, 1, 1, 0], [1, 1, 0, 1], [1, 1, 2, -1]]).transpose()

In [13]:
a = np.array([[2, 0, 0], [4, 1, 1], [-3, 1, -1]])
np.linalg.inv(a)

array([[ 0.5 ,  0.  ,  0.  ],
       [-0.25,  0.5 ,  0.5 ],
       [-1.75,  0.5 , -0.5 ]])

In [14]:
a = sp.Matrix([[-1, 2, 0, 4, 5, -3], [3, -7, 2, 0, 1, 4], [2, -5, 2, 4, 6, 1], [4, -9, 2, -4, -4, 7]])
a.rref()

(Matrix([
 [1, 0, -4, -28, -37, 13],
 [0, 1, -2, -12, -16,  5],
 [0, 0,  0,   0,   0,  0],
 [0, 0,  0,   0,   0,  0]]),
 (0, 1))

In [15]:
x = np.array([[2, 3, 1]]).reshape(-1, 1)
S = np.array([[1, 1, 0], [1, 1, 1], [0, 1, -1]])
S_inv = np.linalg.inv(S)
np.dot(S_inv, x)

array([[0.],
       [2.],
       [1.]])

In [16]:
A_and_T = sp.Matrix([[1, 1, 2, 4, 5, 6], [2, 1, 0, -1, 5, 3], [0, 1, 1, 3, 2, 3]])
A_and_T.rref()

(Matrix([
 [1, 0, 0, -1, 2, 1],
 [0, 1, 0,  1, 1, 1],
 [0, 0, 1,  2, 1, 2]]),
 (0, 1, 2))

In [17]:
A = np.array([[35, 42, 77], [42, 70, 112], [77, 112, 189]])
np.linalg.det(A)

9.748646334628575e-12

In [26]:
A = np.array([[3, 2], [3, 2]])
A_T = A.transpose()
b = np.array([[12, 6]]).reshape(-1, 1)
try:
    np.linalg.inv(np.dot(A_T, A))
except:
    print('역행렬이 없음', np.linalg.det(np.dot(A_T, A)))
#A_T_multiple_A_inv = np.linalg.inv(np.dot(A_T, A))
#x = np.dot(A_T_multiple_A_inv, A_T, b)

역행렬이 없음 0.0


In [22]:
A = sp.Matrix([[1, 3, -2, 0, 2, 0, 0], [2, 6, -5, -2, 4, -3, -1],
[0, 0, 5, 10, 0, 15, 5], [2, 6, 0, 8, 4, 18, 6]])
A.rref()


(Matrix([
 [1, 3, 0, 4, 2, 0,   0],
 [0, 0, 1, 2, 0, 0,   0],
 [0, 0, 0, 0, 0, 1, 1/3],
 [0, 0, 0, 0, 0, 0,   0]]),
 (0, 2, 5))

In [23]:
A = np.array([[2, -3, 0], [1, 3, 0]])
B = np.array([[2, -1, 0], [6, -3, 0]])
A = sp.Matrix(A)
B = sp.Matrix(B)
A.rref(), B.rref()

((Matrix([
  [1, 0, 0],
  [0, 1, 0]]),
  (0, 1)),
 (Matrix([
  [1, -1/2, 0],
  [0,    0, 0]]),
  (0,)))

In [25]:
A = np.array([[2, -3], [1, 3]])
B = np.array([[2, -1], [6, -3]])
np.linalg.det(A), np.linalg.det(B)

(9.000000000000002, 0.0)

In [27]:
A = np.array([[-2, 7, 3], [1, 5, 8], [0, 0, 0]])
np.linalg.det(A)

0.0

In [28]:
A = np.array([[1, 2, 3, 1, 0, 0], [2, 5, 3, 0, 1, 0], [1, 0, 8, 0, 0, 1]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0, 0, -40, 16,  9],
 [0, 1, 0,  13, -5, -3],
 [0, 0, 1,   5, -2, -1]]),
 (0, 1, 2))

In [31]:
A = np.array([[1, 2, 3], [2, 5, 3], [1, 0, 8]])
b = np.array([[1, 3, -1]]).transpose()
np.dot(np.linalg.inv(A), b).round(2)

array([[-1.],
       [ 1.],
       [-0.]])

In [32]:
A = np.array([[0, 0, 0, 1, 10], [1, 1, 1, 1, 7], [27, 9, 3, 1, -11], [64, 16, 4, 1, -14]])
A_sp = sp.Matrix(A)
A_sp.rref()

(Matrix([
 [1, 0, 0, 0,  1],
 [0, 1, 0, 0, -6],
 [0, 0, 1, 0,  2],
 [0, 0, 0, 1, 10]]),
 (0, 1, 2, 3))

In [35]:
A = np.array([[1, 2, 1], [1, 1, 0], [2, -1, 1]])
A_3 = 3 * A
np.linalg.det(A), np.linalg.det(A_3), 27 * 4

(-4.000000000000001, -108.00000000000003, 108)

In [46]:
A = np.array([[2, -3, 1], [4, 2, 2], [1, 0, -2]])
A_sp = sp.Matrix(A)
adj_A = np.array(A_sp.adjugate())
np.dot(A, adj_A)
np.dot((1 / np.linalg.det(A)), adj_A)

array([[0.100000000000000, 0.150000000000000, 0.200000000000000],
       [-0.250000000000000, 0.125000000000000, 0],
       [0.0500000000000000, 0.0750000000000000, -0.400000000000000]],
      dtype=object)

In [59]:
A = np.array([[3, 2, 4], [2, -1, 1], [1, 2, 3]])
b = np.array([[1, 0, 1]]).transpose()
det_A = np.linalg.det(A).round(0)
A[:, 0] = b.transpose()
det_b1 = np.linalg.det(A)
x1 = det_b1 / det_A
x1

-0.2

In [60]:
V = np.array([[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]])
p_x = np.array([[3, -2, -5, 0]]).transpose()
np.dot(np.linalg.inv(V), p_x)

array([[ 4.],
       [ 3.],
       [-5.],
       [ 1.]])