In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, -1], [3, 1, 0]])
b = np.array([[-2, 1], [0, -3], [2, 1]])
np.dot(a, b)

array([[-4, -6],
       [-6,  0]])

In [3]:
a = np.array([[1, 0, 0],
[0, 1, 0],
[-2, 0, 1]])
b = np.array([[1, 0, 0],
[0, 1, 0],
[2, 0, 1]])
np.dot(a, b)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
a = np.array([[4, 3], [6, 5]])
np.linalg.det(a)

1.999999999999998

In [5]:
a = np.array([[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]])
b = np.array([[3, -2, -5, 0]]).reshape(-1, 1)
np.dot(np.linalg.inv(a), b)

array([[ 4.],
       [ 3.],
       [-5.],
       [ 1.]])

In [6]:
a = np.array([[3, 7, 1], [-2, 1, 1], [5, -2, 1]])
np.linalg.det(a)

57.00000000000001

In [7]:
a = np.array([[-1, 2, 3, -1]]).reshape(-1, 1)
b = np.array([[2, 1, 0, 2]]).reshape(-1, 1)
inner_product = 0
for comp in zip(a, b):
    inner_product += comp[0] * comp[1]
int(inner_product)

-2

In [8]:
t1 = np.array([1, 1]).reshape(-1, 1)
t2 = np.array([1, -1]).reshape(-1, 1)
t = np.hstack([t1, t2])
x = np.array([5, -2]).reshape(-1, 1)
y = np.array([3, 4]).reshape(-1, 1)
np.dot(np.linalg.inv(t), x), np.dot(np.linalg.inv(t), y), np.dot(np.linalg.inv(t), x + y)

(array([[1.5],
        [3.5]]),
 array([[ 3.5],
        [-0.5]]),
 array([[5.],
        [3.]]))

In [9]:
A = np.array([[1, 1, 2], [3, 4, 1], [3, 7, 1], [4, 2, 3]])
b = np.array([11, 2, -7, 21]).reshape(-1, 1)
np.dot(np.dot(np.linalg.inv(np.dot(A.transpose(), A)), A.transpose()), b)

array([[ 2.51428571],
       [-2.85714286],
       [ 5.6       ]])

In [10]:
a = np.array([[1, 2, 2], [1, 2, -1], [3, -3, 0]])
np.linalg.det(a)

-27.0

In [11]:
a = np.array([[4, 1], [5, 1]])
np.linalg.det(a)

-0.9999999999999998