In [1]:
import numpy as np

In [2]:
a = np.array([[1, 2, -1], [3, 1, 0]])
b = np.array([[-2, 1], [0, -3], [2, 1]])
np.dot(a, b)

array([[-4, -6],
       [-6,  0]])

In [3]:
a = np.array([[1, 0, 0],
[0, 1, 0],
[-2, 0, 1]])
b = np.array([[1, 0, 0],
[0, 1, 0],
[2, 0, 1]])
np.dot(a, b)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [4]:
a = np.array([[4, 3], [6, 5]])
np.linalg.det(a)

1.999999999999998

In [5]:
a = np.array([[1, 1, 1, 1], [1, 2, 4, 8], [1, 3, 9, 27], [1, 4, 16, 64]])
b = np.array([[3, -2, -5, 0]]).reshape(-1, 1)
np.dot(np.linalg.inv(a), b)

array([[ 4.],
       [ 3.],
       [-5.],
       [ 1.]])

In [6]:
a = np.array([[3, 7, 1], [-2, 1, 1], [5, -2, 1]])
np.linalg.det(a)

57.00000000000001

In [18]:
a = np.array([[-1, 2, 3, -1]]).reshape(-1, 1)
b = np.array([[2, 1, 0, 2]]).reshape(-1, 1)
inner_product = 0
for comp in zip(a, b):
    inner_product += comp[0] * comp[1]
int(inner_product)

-2