In [4]:
import torch
import numpy as np

In [5]:
example_array = np.array([[1, 2], [3, 4]])
ft = torch.FloatTensor(example_array)
ft

tensor([[1., 2.],
        [3., 4.]])

In [6]:
lt = torch.LongTensor(example_array)
lt

tensor([[1, 2],
        [3, 4]])

In [7]:
bt = torch.ByteTensor(example_array)
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [10]:
x = torch.FloatTensor(3, 2, 3)
x

tensor([[[9.1837e-39, 4.6837e-39, 9.9184e-39],
         [9.0000e-39, 1.0561e-38, 1.0653e-38]],

        [[4.1327e-39, 8.9082e-39, 9.8265e-39],
         [9.4592e-39, 1.0561e-38, 1.0745e-38]],

        [[9.9184e-39, 9.6429e-39, 4.6837e-39],
         [4.5000e-39, 4.5918e-39, 4.2245e-39]]])

In [11]:
x = torch.from_numpy(example_array)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [12]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [13]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [16]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.size(), x.shape

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]))

In [18]:
x.dim()

3