In [4]:
import torch
import numpy as np

In [5]:
example_array = np.array([[1, 2], [3, 4]])
ft = torch.FloatTensor(example_array)
ft

tensor([[1., 2.],
        [3., 4.]])

In [6]:
lt = torch.LongTensor(example_array)
lt

tensor([[1, 2],
        [3, 4]])

In [7]:
bt = torch.ByteTensor(example_array)
bt

tensor([[1, 2],
        [3, 4]], dtype=torch.uint8)

In [10]:
x = torch.FloatTensor(3, 2, 3)
x

tensor([[[9.1837e-39, 4.6837e-39, 9.9184e-39],
         [9.0000e-39, 1.0561e-38, 1.0653e-38]],

        [[4.1327e-39, 8.9082e-39, 9.8265e-39],
         [9.4592e-39, 1.0561e-38, 1.0745e-38]],

        [[9.9184e-39, 9.6429e-39, 4.6837e-39],
         [4.5000e-39, 4.5918e-39, 4.2245e-39]]])

In [11]:
x = torch.from_numpy(example_array)
x

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

In [12]:
x.numpy()

array([[1, 2],
       [3, 4]])

In [13]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [16]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.size(), x.shape

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]))

In [18]:
x.dim()

3

In [19]:
a = torch.FloatTensor(np.array([[1, 2], [3, 4]]))
b = torch.FloatTensor(np.array([[2, 2], [3, 3]]))

In [22]:
a + b, a ** b, a == b

(tensor([[3., 4.],
         [6., 7.]]),
 tensor([[ 1.,  4.],
         [27., 64.]]),
 tensor([[False,  True],
         [ True, False]]))

In [29]:
a.add(b), a.mul(b)

(tensor([[3., 4.],
         [6., 7.]]),
 tensor([[ 2.,  4.],
         [ 9., 12.]]))

In [31]:
a.sum(), a.mean()

(tensor(10.), tensor(2.5000))

In [35]:
a.sum(dim=0)

tensor([4., 6.])

In [37]:
y = 1
a + y

tensor([[2., 3.],
        [4., 5.]])

In [43]:
y = torch.FloatTensor([[3], [5]])
z = torch.FloatTensor([[3, 5]])
a + y, a + z

(tensor([[4., 5.],
         [8., 9.]]),
 tensor([[4., 7.],
         [6., 9.]]))

In [44]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.shape

torch.Size([3, 2, 2])

In [45]:
x.view(12), x.view(3, 4), x.view(3, 1, 4)

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]))

In [47]:
x.view(-1), x.view(3, -1), x.view(-1, 1, 4)

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 tensor([[[ 1.,  2.,  3.,  4.]],
 
         [[ 5.,  6.,  7.,  8.]],
 
         [[ 9., 10., 11., 12.]]]))

In [48]:
y = x.view(3, -1)
x.storage().data_ptr() == y.storage().data_ptr()

True

In [49]:
y = x.reshape(3, -1)
x.storage().data_ptr() == y.storage().data_ptr()

True

In [50]:
x = torch.FloatTensor([[[1, 2], [3, 4]]])
x.shape

torch.Size([1, 2, 2])

In [51]:
x.squeeze()

tensor([[1., 2.],
        [3., 4.]])

In [53]:
x.squeeze(0).shape, x.squeeze(1).shape

(torch.Size([2, 2]), torch.Size([1, 2, 2]))

In [54]:
y = x.squeeze()
y

tensor([[1., 2.],
        [3., 4.]])

In [56]:
y.unsqueeze(0), y.unsqueeze(1), y.unsqueeze(-1), y.unsqueeze(-1).shape

(tensor([[[1., 2.],
          [3., 4.]]]),
 tensor([[[1., 2.]],
 
         [[3., 4.]]]),
 tensor([[[1.],
          [2.]],
 
         [[3.],
          [4.]]]),
 torch.Size([2, 2, 1]))

In [57]:
y.reshape(2, 2, 1)

tensor([[[1.],
         [2.]],

        [[3.],
         [4.]]])