In [1]:
import torch
import numpy as np

In [3]:
x = torch.FloatTensor([i + 1 for i in range(6)]).reshape(3, -1)
y = torch.FloatTensor([1, 2]).expand(2, 2)
x, y

(tensor([[1., 2.],
         [3., 4.],
         [5., 6.]]),
 tensor([[1., 2.],
         [1., 2.]]))

In [4]:
x.matmul(y)

tensor([[ 3.,  6.],
        [ 7., 14.],
        [11., 22.]])

In [7]:
x = torch.randperm(3 * 3 * 2).reshape(3, 3, 2)
y = torch.randperm(3 * 2 * 3).reshape(3, 2, 3)
x, y

(tensor([[[11, 15],
          [ 5, 14],
          [ 2,  3]],
 
         [[17,  6],
          [ 9,  8],
          [10,  4]],
 
         [[16,  0],
          [ 7, 13],
          [12,  1]]]),
 tensor([[[ 1,  9, 12],
          [10,  8,  5]],
 
         [[ 2, 17, 14],
          [13,  3,  0]],
 
         [[15,  6,  7],
          [16,  4, 11]]]))

In [8]:
x.bmm(y)

tensor([[[161, 219, 207],
         [145, 157, 130],
         [ 32,  42,  39]],

        [[112, 307, 238],
         [122, 177, 126],
         [ 72, 182, 140]],

        [[240,  96, 112],
         [313,  94, 192],
         [196,  76,  95]]])