In [2]:
import torch
import numpy as np

In [3]:
ft = torch.FloatTensor([[1, 2], [3, 4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [4]:
ft = torch.LongTensor(3, 2)
ft

tensor([[0, 0],
        [0, 0],
        [0, 0]])

In [5]:
x = np.array([[1, 2], [3, 4]])
torch.from_numpy(x).numpy()

array([[1, 2],
       [3, 4]])

In [6]:
x = torch.FloatTensor([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])
x.size(), x.shape

(torch.Size([3, 2, 2]), torch.Size([3, 2, 2]))

In [7]:
x.dim(), len(x.size())

(3, 3)